In [4]:
import pandas as pd

In [23]:
df = pd.read_csv('../data2/dataset.csv')
df.head()

,url,flat_id,price,description,total_area,living_area,address,image_urls,image_count,image_paths,build_year,price_rub,floor_num,total_floors
0,https://www.cian.ru/sale/flat/327744278/?conte...,327744278,95 000 000 ₽,Просторная видовая 3-комнатная квартира в клуб...,101.5,60.4,"Москва, ЗАО, р-н Раменки, Ломоносовский просп....",['https://images.cdn-cian.ru/images/2827655066...,68,"['data/raw/images/327744278/0.jpg', 'data/raw/...",NaN,95000000.0,9,12
1,https://www.cian.ru/sale/flat/326878984/?conte...,326878984,42 000 000 ₽,"Роскошная 4х-комнатная квартира, без отделки, ...",112.3,NaN,"Москва, ЦАО, р-н Пресненский, Шмитовский проез...",['https://images.cdn-cian.ru/images/2826616067...,12,"['data/raw/images/326878984/0.jpg', 'data/raw/...",2024.0,42000000.0,13,50
2,https://www.cian.ru/sale/flat/323336526/?conte...,323336526,87 179 200 ₽,Рассрочка 0% на 6 месяцев.\n\nLumin House - кл...,82.4,26.4,"Москва, ЦАО, р-н Таганский, Славянская пл., 2/...",['https://images.cdn-cian.ru/images/kvartira-m...,30,"['data/raw/images/323336526/0.jpg', 'data/raw/...",2022.0,87179200.0,5,8
3,https://www.cian.ru/sale/flat/325174580/?conte...,325174580,72 500 000 ₽,Лот 58728. Евгений Аристов.\n\nПредставляем ва...,60.4,45.0,"Москва, ЦАО, р-н Замоскворечье, Садовническая ...",['https://images.cdn-cian.ru/images/2741911645...,30,"['data/raw/images/325174580/0.jpg', 'data/raw/...",2016.0,72500000.0,2,7
4,https://www.cian.ru/sale/flat/322505468/?conte...,322505468,330 000 000 ₽,ЭКСКЛЮЗИВНАЯ ГОРОДСКАЯ ВИЛЛА В ЦЕНТРЕ МОСКВЫ\n...,324.0,230.0,"Москва, ЦАО, р-н Тверской, Долгоруковская ул.,...",['https://images.cdn-cian.ru/images/2652688141...,42,"['data/raw/images/322505468/0.jpg', 'data/raw/...",2021.0,330000000.0,3,3

In [24]:
list(df.columns),len(list(df.columns))

(['url',
  'flat_id',
  'price',
  'description',
  'total_area',
  'living_area',
  'address',
  'image_urls',
  'image_count',
  'image_paths',
  'build_year',
  'price_rub',
  'floor_num',
  'total_floors'],
 14)

In [25]:
df['description'][1]

'Роскошная 4х-комнатная квартира, без отделки, в Жилом Комплексе бизнес-класса "HEADLINER".Общая площадь 112 кв.м. Планировка: кухня-гостиная, три спальни, три с/узла, постирочная, гардеробная. \nЖК HEADLINER - логическое архитектурное продолжение легендарного МОСКВА-СИТИ.\n\n\nУчастник ассоциации агентств элитной недвижимости AREA.\nУзнать больше'

In [26]:
df.describe()

,flat_id,total_area,living_area,image_count,build_year,price_rub,floor_num,total_floors
count,3.520000e+02,352.000000,178.000000,352.000000,265.000000,3.520000e+02,352.000000,352.000000
mean,3.236326e+08,145.875142,85.917978,44.801136,2002.894340,1.881678e+08,10.201705,17.795455
std,6.109665e+06,89.450475,50.983137,18.216338,33.929352,1.618421e+08,10.923547,15.756270
min,2.587836e+08,32.000000,12.300000,4.000000,1900.000000,1.590000e+07,1.000000,3.000000
25%,3.228577e+08,90.000000,52.250000,32.000000,2005.000000,7.765250e+07,4.000000,7.000000
50%,3.252925e+08,127.900000,76.500000,42.000000,2017.000000,1.394000e+08,6.000000,11.000000
75%,3.266981e+08,173.050000,102.350000,56.000000,2022.000000,2.575375e+08,11.000000,22.000000
max,3.277821e+08,877.000000,323.000000,100.000000,2026.000000,1.400000e+09,69.000000,79.000000

In [27]:
df.loc[4,:]

url             https://www.cian.ru/sale/flat/322505468/?conte...
flat_id                                                 322505468
price                                               330 000 000 ₽
description     ЭКСКЛЮЗИВНАЯ ГОРОДСКАЯ ВИЛЛА В ЦЕНТРЕ МОСКВЫ\n...
total_area                                                  324.0
living_area                                                 230.0
address         Москва, ЦАО, р-н Тверской, Долгоруковская ул.,...
image_urls      ['https://images.cdn-cian.ru/images/2652688141...
image_count                                                    42
image_paths     ['data/raw/images/322505468/0.jpg', 'data/raw/...
build_year                                                 2021.0
price_rub                                             330000000.0
floor_num                                                       3
total_floors                                                    3
Name: 4, dtype: object

In [28]:
df.shape

(352, 14)

In [20]:
df2 = pd.read_csv('../data/dataset.csv')
df2.head()

,flat_id,url,scraped_at,price_rub,price_per_m2,rooms,is_studio,total_area,living_area,kitchen_area,...,image_count_local,image_paths_local,image_urls,description,price_raw,floor_raw,rooms_raw,build_year_raw,metro_raw,factoids_raw
0,324549697,https://www.cian.ru/sale/flat/324549697/?conte...,2026-03-22 13:13:00,1.550000e+09,1132213.0,3.0,0,136.9,NaN,14.9,...,0,NaN,https://images.cdn-cian.ru/images/2746884915-1...,"ID: 584582\nИсторический центр столицы, старей...",155 000 000 ₽,6 из 8,3.0,1910.0,Смоленская\n3 мин.\nКропоткинская\n15 мин.\nАр...,"{""общая площадь"": ""136,9 м²"", ""площадь кухни"":..."
1,320335475,https://www.cian.ru/sale/flat/320335475/?conte...,2026-03-22 13:13:01,NaN,NaN,2.0,0,91.1,NaN,NaN,...,0,NaN,https://images.cdn-cian.ru/images/2831713354-1...,Прямая продажа от застройщика! Продаётся 2-к к...,NaN,3 из 11,2.0,2026.0,Павелецкая\n16 мин.\nПролетарская\n19 мин.\nКр...,"{""общая площадь"": ""91,1 м²"", ""этаж"": ""3 из 11""..."
2,326880398,https://www.cian.ru/sale/flat/326880398/?conte...,2026-03-22 13:13:08,8.250000e+08,996377.0,3.0,0,82.8,50.0,26.2,...,0,NaN,https://images.cdn-cian.ru/images/kvartira-mos...,"Обременений нет, полная стоимость в договоре к...",82 500 000 ₽,6 из 36,3.0,2025.0,ЦСКА\n13 мин.\nПетровский Парк\n13 мин.\nДинам...,"{""общая площадь"": ""82,8 м²"", ""жилая площадь"": ..."
3,326438271,https://www.cian.ru/sale/flat/326438271/?conte...,2026-03-22 13:13:07,3.100000e+08,534483.0,2.0,0,58.0,40.0,9.0,...,0,NaN,https://images.cdn-cian.ru/images/kvartira-mos...,Престижный и зелёный район !\n\nПродается потр...,31 000 000 ₽,4 из 7,2.0,1958.0,Динамо\n3 мин.\nПетровский Парк\n7 мин.\nБелор...,"{""общая площадь"": ""58 м²"", ""жилая площадь"": ""4..."
4,323005752,https://www.cian.ru/sale/flat/323005752/?conte...,2026-03-22 13:13:15,6.167388e+08,855394.0,2.0,0,72.1,45.2,NaN,...,0,NaN,https://images.cdn-cian.ru/images/2798545854-1...,Жилой квартал премиум-класса Prime Park — оази...,61 673 881 ₽,30 из 41,2.0,NaN,Динамо\n15 мин.\nАэропорт\n13 мин.\nПетровский...,"{""общая площадь"": ""72,1 м²"", ""жилая площадь"": ..."

In [27]:
len(df2['district'])

28

In [16]:
(list(df2.columns))

['flat_id',
 'url',
 'scraped_at',
 'price_rub',
 'price_per_m2',
 'rooms',
 'is_studio',
 'total_area',
 'living_area',
 'kitchen_area',
 'living_ratio',
 'kitchen_ratio',
 'non_living_area',
 'floor',
 'floors_total',
 'is_first_floor',
 'is_last_floor',
 'floor_ratio',
 'floors_above',
 'build_year',
 'building_age',
 'building_type',
 'building_type_cat',
 'building_type_code',
 'ceiling_height',
 'renovation',
 'renovation_cat',
 'has_elevator_bin',
 'has_parking_obj',
 'has_balcony_obj',
 'bathroom_separate',
 'elevator',
 'parking_type',
 'balcony_type',
 'bathroom',
 'heating',
 'windows',
 'desc_len',
 'desc_word_count',
 'has_balcony',
 'has_loggia',
 'has_parking',
 'has_furniture',
 'has_renovated',
 'has_mortgage',
 'has_new_building',
 'has_view',
 'has_alarm',
 'metro_station',
 'metro_minutes',
 'metro_by_foot',
 'district',
 'address',
 'image_count',
 'image_count_local',
 'image_paths_local',
 'image_urls',
 'description',
 'price_raw',
 'floor_raw',
 'rooms_raw',
 'build_year_raw',
 'metro_raw',
 'factoids_raw']

In [21]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 50 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   flat_id            28 non-null     int64
 1   url                28 non-null     object
 2   scraped_at         28 non-null     object
 3   price_rub          18 non-null     float64
 4   price_per_m2       18 non-null     float64
 5   rooms              27 non-null     float64
 6   is_studio          28 non-null     int64
 7   total_area         28 non-null     float64
 8   living_area        18 non-null     float64
 9   kitchen_area       18 non-null     float64
 10  living_ratio       18 non-null     float64
 11  kitchen_ratio      18 non-null     float64
 12  non_living_area    18 non-null     float64
 13  floor              28 non-null     int64
 14  floors_total       28 non-null     int64
 15  is_first_floor     28 non-null     int64
 16  is_last_floor      28 non-null     int64
 17  floor_ratio        28 non-null     float64
 18  floors_above       28 non-null     int64
 19  build_year         23 non-null     float64
 20  building_age       23 non-null     float64
 21  renovation         10 non-null     object
 22  renovation_cat     0 non-null      float64
 23  desc_len           28 non-null     int64
 24  desc_word_count    28 non-null     int64
 25  has_balcony        28 non-null     int64
 26  has_loggia         28 non-null     int64
 27  has_parking        28 non-null     int64
 28  has_furniture      28 non-null     int64
 29  has_renovated      28 non-null     int64
 30  has_mortgage       28 non-null     int64
 31  has_new_building   28 non-null     int64
 32  has_view           28 non-null     int64
 33  has_alarm          28 non-null     int64
 34  metro_station      28 non-null     object
 35  metro_minutes      28 non-null     int64
 36  metro_by_foot      28 non-null     int64
 37  district           0 non-null      float64
 38  address            28 non-null     object
 39  image_count        28 non-null     int64
 40  image_count_local  28 non-null     int64
 41  image_paths_local  0 non-null      float64
 42  image_urls         28 non-null     object
 43  description        28 non-null     object
 44  price_raw          18 non-null     object
 45  floor_raw          28 non-null     object
 46  rooms_raw          27 non-null     float64
 47  build_year_raw     23 non-null     float64
 48  metro_raw          28 non-null     object
 49  factoids_raw       28 non-null     object
dtypes: float64(17), int64(22), object(11)
memory usage: 11.1+ KB

In [18]:

print(df2["factoids_raw"].dropna().head(3).to_list())

['{"общая площадь": "137\xa0м²", "жилая площадь": "74\xa0м²", "площадь кухни": "15\xa0м²", "этаж": "6 из 8"}', '{"общая площадь": "76\xa0м²", "жилая площадь": "27,3\xa0м²", "площадь кухни": "22,4\xa0м²", "этаж": "2 из 9", "год сдачи": "2027", "дом": "Не сдан", "отделка": "Без отделки"}', '{"общая площадь": "118,5\xa0м²", "площадь кухни": "23,4\xa0м²", "этаж": "15 из 22", "год постройки": "2007"}']

In [19]:
import json
for row in df2["factoids_raw"].dropna().head(3):
    print(json.loads(row))
    print()

{'общая площадь': '137\xa0м²', 'жилая площадь': '74\xa0м²', 'площадь кухни': '15\xa0м²', 'этаж': '6 из 8'}

{'общая площадь': '76\xa0м²', 'жилая площадь': '27,3\xa0м²', 'площадь кухни': '22,4\xa0м²', 'этаж': '2 из 9', 'год сдачи': '2027', 'дом': 'Не сдан', 'отделка': 'Без отделки'}

{'общая площадь': '118,5\xa0м²', 'площадь кухни': '23,4\xa0м²', 'этаж': '15 из 22', 'год постройки': '2007'}